apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: app
  labels:
    app: voltra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voltra-app
  template:
    metadata:
      labels:
        app: voltra-app
      annotations:
        # Enable Vault Agent Injector
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "webapp-role"

        # Define secret path and custom file output formatting
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-app-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-app-role" -}}
          username={{ .Data.username }}
          password={{ .Data.password }}
          {{- end -}}
    spec:
      serviceAccountName: webapp-sa
      containers:
      - name: webapp
        image: bilal7191/voltra-app:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http
        env:
            - name: CREDS_PATH
              value: /vault/secrets/db-creds
            - name: DB_HOST
              value: postgres-postgresql.pg-database.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: appdb
            - name: CREDS_POLL_SECONDS
              value: "2"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voltra-app
  namespace: app
spec:
  type: NodePort
  selector:
    app: voltra-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080